print("Hello ! , Person")
name = input("What is your Name ?")
name2 = input("What is your Age ?")
name3 = input ("What is your Gender ?")
output = f"Hello , {name} {name2} {name3}"
print(output)
print()
print()
print("Ok then, Lets do some Math")
print()
f1 = input("Enter the First Number for Addition")
f2 = input("Enter the Second Number  for Addition")
print()
print(int(f1) + int(f2))
print()
print("Hurrah! I just did math , now lets do more operations of math")
print()
f3 = input("Enter the First Number for Subtraction")
f4 = input("Enter the Second Number  for Subtraction")
print()
print(int(f3) - int(f4))
f5 = input("Enter the First Number for Multiplication")
f6 = input("Enter the Second Number  for Multiplication")
print()
print(int(f5) * int(f6))
f7 = input("Enter the First Number for Division")
f8 = input("Enter the Second Number  for Division")
print()
print(int(f7) / int(f8))
f9 = input("Enter the First Number for Exponential Powers")
f10 = input("Enter the Second Number  for Exponential Powers")
print()
print(int(f9) ** int(f10))
print()
f11 = input("Enter Number to find Sqaure Root")
print(int(f11)**0.5)
print()
print("Thanks for visiting my mini calculator")
